app = "helix-rss"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  INTERNAL_URL = "0.0.0.0"
  DISCORD_PORT = "3131"
  SQLITE_DATA = "/app/data"

[http_service]
  internal_port = 3131
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/health"

[[mounts]]
  source = "helix_data"
  destination = "/app/data"
