app = "helix-rss"
primary_region = "ord"

[build]

[mounts]
  source = "helix_data"
  destination = "/data"

[env]
  CADDY_ENABLED = "false"
  SQLITE_DATA = "/data"

[http_service]
  internal_port = 3131
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
