blank_issues_enabled: false
contact_links:
  - name: "Wiki"
    url: "https://github.com/HELIX-Origin/Discord-rSS/wiki"
    about: "The wiki contains detailed documentation, guides, and resources related to the HELIX Origin project. It serves as a valuable reference for developers and contributors looking to understand the project's architecture, features, and best practices."