name: Feature Request
about: Propose a feature or optional Discohook/service integration.
title: "[FEAT] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "## Feature Request"
  - type: textarea
    id: description
    attributes:
      label: Description
      required: true
